local L = LibStub("AceLocale-3.0"):GetLocale("MyBags")

BINDING_HEADER_MYBAGSHEADER = L["BINDING_HEADER_MYBAGSHEADER"]
BINDING_NAME_MYINVENTORY    = L["BINDING_NAME_MYINVENTORY"]
BINDING_NAME_MYBANK         = L["BINDING_NAME_MYBANK"]
BINDING_NAME_MYEQUIPMENT    = L["BINDING_NAME_MYEQUIPMENT"]
