-- Version : English - Ramble 

MYINVENTORY_NAME = "MyInventory"
MYINVENTORY_DESCRIPTION = "All in one inventory mod"

MYINVENTORYFRAME_TITLE = "Inventory"

-- SLASHCOMMANDS
--[[
MYINVENTORY_COMMANDS    = {"/myinventory", "/mi"}
MYINVENTORY_CMD_OPTIONS = {
	MYBAGS_CMD_OPT_TOGGLE,			-- done
	MYBAGS_CMD_OPT_FREEZE,			-- done
	MYBAGS_CMD_OPT_NOESC,				-- done
	MYBAGS_CMD_OPT_COLUMNS,			-- done
	MYBAGS_CMD_OPT_REPLACE,			-- done
	MYBAGS_CMD_OPT_BAG,					-- done
	MYBAGS_CMD_OPT_GRAPHICS,		-- ????
	MYBAGS_CMD_OPT_HIGHLIGHT,		-- done
	MYBAGS_CMD_OPT_LOCK,				-- done
	MYBAGS_CMD_OPT_TITLE,				-- done
	MYBAGS_CMD_OPT_CASH,				-- done
	MYBAGS_CMD_OPT_BUTTONS,			-- done
	MYBAGS_CMD_OPT_AIOI,				-- done
	MYBAGS_CMD_OPT_REVERSE,			-- done
	MYBAGS_CMD_OPT_BORDER,			-- done
	MYBAGS_CMD_OPT_PLAYERSEL,		-- done
	MYBAGS_CMD_OPT_COUNT,
	MYBAGS_CMD_OPT_SCALE,
	MYBAGS_CMD_OPT_STRATA,
	MYBAGS_CMD_OPT_ANCHOR,
	MYBAGS_CMD_RESET,
	MYBAGS_CMD_OPT_SLOTCOLOR,
	MYBAGS_CMD_OPT_COMPANION,
}
]]